FROM ubuntu:22.04

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    git \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-ttf-dev \
    libsdl2-mixer-dev \
    gdb \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*

# Создаем обычного пользователя
RUN useradd -m -s /bin/bash developer && \
    mkdir -p /home/developer && \
    chown developer:developer /home/developer

USER developer
WORKDIR /home/developer